version: "3"

services:
  fuel-app:
    build:
      context: .
      dockerfile: ./docker/fuel-app/Dockerfile
    volumes:
      - ./docker/fuel-app/php.ini:/usr/local/etc/php/php.ini
      - ./fuel-app:/var/www
    working_dir: /var/www
    ports:
      - "8080:8080"
    command: "php -S 0.0.0.0:8080 -t public"
  fuel_db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: fuelphp_sample
      MYSQL_USER: fuelphp_sample
      MYSQL_PASSWORD: fuelphp_sample_pw